package com.boge.demo.mapper;

import com.boge.demo.dataobject.PromoteDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PromoteDOMapper {

    PromoteDO selectByItemId(Integer itemid);

    int updateIsAddorder(Integer itemid, Integer isaddorder);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST 2019
     */
    int deleteByPrimaryKey(Integer promoteid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST 2019
     */
    int insert(PromoteDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST 2019
     */
    int insertSelective(PromoteDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST 2019
     */
    PromoteDO selectByPrimaryKey(Integer promoteid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST 2019
     */
    int updateByPrimaryKeySelective(PromoteDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST 2019
     */
    int updateByPrimaryKey(PromoteDO record);
}