package com.boge.demo.mapper;

import com.boge.demo.dataobject.UserDO;
import com.boge.demo.service.model.UserModel;
import org.springframework.stereotype.Repository;

@Repository
public interface UserDOMapper {


    int isUserExist(String username);

    int isPhoneExist(String telphone);

    UserDO getUserByUsername(String username);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Jul 02 10:09:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Jul 02 10:09:50 CST 2019
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Jul 02 10:09:50 CST 2019
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Jul 02 10:09:50 CST 2019
     */
    UserDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Jul 02 10:09:50 CST 2019
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Jul 02 10:09:50 CST 2019
     */
    int updateByPrimaryKey(UserDO record);
}