package com.boge.demo.controller.VO;





import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;


public class PromoteVO implements Serializable{

    private Integer promoteid;


    private Integer itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote.starttime
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST19
     */
    private String starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote.promoteprice
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST 2019
     */
    private BigDecimal promoteprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote.lasttime
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST 2019
     */
    private String lasttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote.isaddorder
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST 2019
     */
    private Integer isaddorder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote.promoteid
     *
     * @return the value of promote.promoteid
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST 2019
     */
    public Integer getPromoteid() {
        return promoteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote.promoteid
     *
     * @param promoteid the value for promote.promoteid
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST 2019
     */
    public void setPromoteid(Integer promoteid) {
        this.promoteid = promoteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote.itemid
     *
     * @return the value of promote.itemid
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST 2019
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote.itemid
     *
     * @param itemid the value for promote.itemid
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST 2019
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote.starttime
     *
     * @return the value of promote.starttime
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST 2019
     */

    public String getStarttime() {
        return starttime;
    }

    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }

    public String getLasttime() {
        return lasttime;
    }

    public void setLasttime(String lasttime) {
        this.lasttime = lasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote.promoteprice
     *
     * @return the value of promote.promoteprice
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST 2019
     */
    public BigDecimal getPromoteprice() {
        return promoteprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote.promoteprice
     *
     * @param promoteprice the value for promote.promoteprice
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST 2019
     */
    public void setPromoteprice(BigDecimal promoteprice) {
        this.promoteprice = promoteprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote.lasttime
     *
     * @return the value of promote.lasttime
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST 2019
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote.lasttime
     *
     * @param lasttime the value for promote.lasttime
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST 2019
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote.isaddorder
     *
     * @return the value of promote.isaddorder
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST 2019
     */
    public Integer getIsaddorder() {
        return isaddorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote.isaddorder
     *
     * @param isaddorder the value for promote.isaddorder
     *
     * @mbg.generated Tue Jul 02 11:14:26 CST 2019
     */
    public void setIsaddorder(Integer isaddorder) {
        this.isaddorder = isaddorder;
    }

    @Override
    public String toString() {
        return "PromoteDO{" +
                "promoteid=" + promoteid +
                ", itemid=" + itemid +
                ", starttime=" + starttime +
                ", promoteprice=" + promoteprice +
                ", lasttime=" + lasttime +
                ", isaddorder=" + isaddorder +
                '}';
    }
}