package com.boge.demo.dataobject;

import java.math.BigDecimal;

public class ItemDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.id
     *
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.itemname
     *
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */
    private String itemname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.price
     *
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.des
     *
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.itemimg
     *
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */
    private String itemimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.sales
     *
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */
    private Integer sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.stocknum
     *
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.id
     *
     * @return the value of item.id
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.id
     *
     * @param id the value for item.id
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.itemname
     *
     * @return the value of item.itemname
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */
    public String getItemname() {
        return itemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.itemname
     *
     * @param itemname the value for item.itemname
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */
    public void setItemname(String itemname) {
        this.itemname = itemname == null ? null : itemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.price
     *
     * @return the value of item.price
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.price
     *
     * @param price the value for item.price
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.des
     *
     * @return the value of item.des
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.des
     *
     * @param des the value for item.des
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.itemimg
     *
     * @return the value of item.itemimg
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */
    public String getItemimg() {
        return itemimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.itemimg
     *
     * @param itemimg the value for item.itemimg
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */
    public void setItemimg(String itemimg) {
        this.itemimg = itemimg == null ? null : itemimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.sales
     *
     * @return the value of item.sales
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.sales
     *
     * @param sales the value for item.sales
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.stocknum
     *
     * @return the value of item.stocknum
     *
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.stocknum
     *
     * @param stocknum the value for item.stocknum
     *
     * @mbg.generated Tue Jul 02 10:14:00 CST 2019
     */

}